// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIUdemy.Entities;

#nullable disable

namespace WebAPIUdemy.Migrations
{
    [DbContext(typeof(DBDbContext))]
    [Migration("20231016175157_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPIUdemy.Models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("city");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5822b3e4-f50a-4bb5-be5e-70a6474dc041"),
                            CityName = "Glasgow"
                        },
                        new
                        {
                            Id = new Guid("f65dee5c-a3bb-4b8e-a12c-78b6e3e7e517"),
                            CityName = "Aberdeen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
